/* tslint:disable */
/* eslint-disable */
/**
 * PlanningPoker.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FinishedStoryDto
 */
export interface FinishedStoryDto {
    /**
     * 
     * @type {number}
     * @memberof FinishedStoryDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof FinishedStoryDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinishedStoryDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FinishedStoryDto
     */
    'voteValue'?: number;
}

