/* tslint:disable */
/* eslint-disable */
/**
 * PlanningPoker.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VoteDto } from './vote-dto';

/**
 * 
 * @export
 * @interface StoryDto
 */
export interface StoryDto {
    /**
     * 
     * @type {number}
     * @memberof StoryDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof StoryDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoryDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StoryDto
     */
    'inProgress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StoryDto
     */
    'isEstimated'?: boolean;
    /**
     * 
     * @type {Array<VoteDto>}
     * @memberof StoryDto
     */
    'votes'?: Array<VoteDto> | null;
}

